version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: mcp-neo4j-dev
    environment:
      NEO4J_AUTH: neo4j/development
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*
      NEO4J_dbms_memory_heap_initial_size: 512m
      NEO4J_dbms_memory_heap_max_size: 1G
      NEO4J_dbms_memory_pagecache_size: 512m
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - neo4j-network
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p development 'RETURN 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  neo4j-test:
    image: neo4j:5.15-community
    container_name: mcp-neo4j-test
    environment:
      NEO4J_AUTH: neo4j/test
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*
      NEO4J_dbms_memory_heap_initial_size: 256m
      NEO4J_dbms_memory_heap_max_size: 512m
      NEO4J_dbms_memory_pagecache_size: 256m
    ports:
      - "7475:7474"  # HTTP
      - "7688:7687"  # Bolt
    volumes:
      - neo4j_test_data:/data
      - neo4j_test_logs:/logs
      - neo4j_test_import:/var/lib/neo4j/import
      - neo4j_test_plugins:/plugins
    networks:
      - neo4j-network
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p test 'RETURN 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local
  neo4j_test_data:
    driver: local
  neo4j_test_logs:
    driver: local
  neo4j_test_import:
    driver: local
  neo4j_test_plugins:
    driver: local

networks:
  neo4j-network:
    driver: bridge
