name: Daily Version Bump

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight UTC
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for accessing git tags
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Setup Python environment
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install python-semantic-release

      - name: Run semantic-release (version bump if needed)
        id: semantic
        run: |
          source .venv/bin/activate
          NEW_VERSION=$(semantic-release version)
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        if: env.NEW_VERSION
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: release ${{ env.NEW_VERSION }}"
          title: "chore: release ${{ env.NEW_VERSION }}"
          body: "Automated version bump to ${{ env.NEW_VERSION }}"
          branch: "release/${{ env.NEW_VERSION }}"
          base: "main"
