name: Daily Version Bump

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight UTC
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for accessing git tags
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Setup Python environment
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install python-semantic-release

      - name: Run semantic-release (version bump if needed)
        run: |
          source .venv/bin/activate
          semantic-release version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
